### ISSUE TITLE
Label in checkbox is not match

### ISSUE THREAD

**Issue by wahyuabied** [ricoarisandyw/ArisanForm#1]
i got bug at ur library (Bug at Checkbox)
here are the pictures
![WhatsApp Image 2019-06-14 at 00 42 53(2)](https://user-images.githubusercontent.com/26244728/59455130-c0c81c80-8e3d-11e9-99a8-c4b5eb730868.jpeg)

**Comment by ricoarisandyw** [comment]
Hei, thanks for reporting We have fix this issue in version 1.7.0
