### ISSUE TITLE
Date Label is not match_parent

### ISSUE THREAD

**Issue by wahyuabied** [ricoarisandyw/ArisanForm#2]
Hey mr, can u fix this little fucking bug.........
its simple but really annoying

![WhatsApp Image 2019-06-14 at 00 42 53(3)](https://user-images.githubusercontent.com/26244728/59455235-f7059c00-8e3d-11e9-8d83-ff3544dfaa93.jpeg)

**Comment by ricoarisandyw** [comment]
hei, thanks for reporting. We have fix it in version 1.7.0
