### ISSUE TITLE
AddListener on form

### ISSUE THREAD

**Issue by julnegre** [ricoarisandyw/ArisanForm#4]
Hi, 
i start using your great library today, but i have one question with the event addListener. 
I dont know how you get another view under the listener ?

```
form.addListener("elem_6", new ArisanListener.OnCondition() {
            @Override
            public void onValue(String value, FormAdapter adapter) {
                   if( "VALUE".equals(value) ){                
                        FormModel element = new KotlinFilter().findFieldByName("elem_7",form.getFieldModels());
                        element.getView().setVisibility(View.GONE);  // HOW ... ?
                    } else {
                        element.getView().setVisibility(View.VISIBLE);  // HOW ... ?
                    }
....
```

Thanks in advance !

**Comment by ricoarisandyw** [comment]
Wow. first thanks for using my library.

Modify view is not using **FormModel**. **FormModel** is model that contains information of **Field** which contain **@Form**.

For Modifying View you use FormViewHolder.  Let me give an example.

```java
 vForm.addListener("category", (value , adapter) -> {
            
            adapter.findViewHolderByName("elem_7").view.mCheckboxLabel.setVisibility(GONE);

        });
```
Sorry if it still long code. Explanation :

1. use `findViewHolderByName('elem_7')` to gain **FormViewHolder**
2. **FormViewHolder** have so many variable that determine view like **mCheckboxLabel** for label of checkbox and **mCheckboxParent** for whole checkbox in that field.
3. **mCheckboxLabel and others variable** is view components, so you can use **setVisibility** on it.
