### ISSUE TITLE
Get Spinner index instead of the text value

### ISSUE THREAD

**Issue by MatheusZickuhr** [ricoarisandyw/ArisanForm#5]
As the title says, is possible to do that?

**Comment by ricoarisandyw** [comment]
Sorry, but we are not provide it because there are other _form type_ that not using _index_ such as EditText. You can use `indexOf ` on array if you want get the position/index.

Example :
```java
String[] fruits = ["apple", "banana", "cherry"];

//in listener
vForm.addListener("category", (value , adapter) -> {
        int index = Arrays.asList(Nature.DATA_CATEGORY).indexOf(value);
});
```
