### ISSUE TITLE
Form.TIME does not work properly

### ISSUE THREAD

**Issue by MatheusZickuhr** [ricoarisandyw/ArisanForm#6]
After pick any time, the field is just set to a date (01-01-1970).

![Screenshot_1578406091](https://user-images.githubusercontent.com/37124939/71901057-db494680-313d-11ea-8301-2a82cef9fde0.png)

![Screenshot_1578406107](https://user-images.githubusercontent.com/37124939/71901063-e13f2780-313d-11ea-87c8-6ed9f40d35be.png)

**Comment by MatheusZickuhr** [comment]
For some reason if I use the form annotation like this (with format):  

`@Form(label = "Hora", type = Form.TIME, position = 6, format = "HH:MM")`

the bug does not happen.

**Comment by ricoarisandyw** [comment]
Thanks @MatheusZickuhr for using my library.
Happy to hear your problem have solved. That was good idea for give default format for **Form.Time**, Immediately I will work on it and check for another **Form**.
